version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus:/etc/prometheus
      - /mnt/Storage1/prometheus:/prometheus
    restart: unless-stopped
    user: "1000:1000"
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
networks:
  default:
    name: traefik-proxy
    external: true
