version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1004
      - PGID=1005
      - TZ=Europe/Stockholm
    volumes:
      - /etc/radarr:/config
      - /mnt/Storage1/MediaLibrary/shared:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=web, websecure"
      - "traefik.http.routers.radarr.rule=Host(`radarr.homepot.io`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=production"
      - "traefik.docker.network=traefik-proxy"
