version: "3"

services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    ports:
      - 8081:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - PUID=1003
      - PGID=1005
      - TZ=Europe/Stockholm
      - WEBUI_PORT=8080
    volumes:
      - /etc/qbt:/config
      - /mnt/Storage1/MediaLibrary/shared/torrents:/downloads
